version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../../apps/frontend:/app
      - /app/node_modules  # Prevent local node_modules from overwriting
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
