FROM oven/bun:1
WORKDIR /app
COPY package.json bun.lock turbo.json ./
COPY apps ./apps
COPY packages ./packages
RUN bun install --frozen-lockfile
WORKDIR /app/apps/frontend
EXPOSE 5173
CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]
