FROM oven/bun:1
WORKDIR /app
ENV DATABASE_URL=postgresql://user:password@localhost:5432/database
COPY package.json bun.lock turbo.json ./
COPY apps ./apps
COPY packages ./packages
RUN bun install --frozen-lockfile
RUN bun run db:generate
WORKDIR /app/apps/http
EXPOSE 3000
CMD ["bun", "--watch", "src/index.ts"]
