FROM oven/bun:1 AS builder
WORKDIR /app
ENV DATABASE_URL=postgresql://user:password@localhost:5432/database
COPY package.json bun.lock turbo.json ./
COPY apps ./apps
COPY packages ./packages
RUN bun install --frozen-lockfile
RUN bun run --filter http build

FROM oven/bun:1-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/http/package.json ./apps/http/package.json
COPY --from=builder /app/apps/http/dist ./apps/http/dist
COPY --from=builder /app/packages/db/package.json ./packages/db/package.json
COPY --from=builder /app/packages/db/dist ./packages/db/dist
COPY --from=builder /app/packages/db/generated ./packages/db/generated
EXPOSE 3000
CMD ["bun", "apps/http/dist/index.js"]
