# --------------------
# Stage 1: Install Dependencies (from root)
# --------------------
FROM node:20-alpine AS installer

WORKDIR /app

ARG DATABASE_URL
# Enable Corepack for npm v9+ support
RUN corepack enable npm

# Accept DATABASE_URL as build ARG
ENV DATABASE_URL=${DATABASE_URL}

# Add any native deps
RUN apk add --no-cache openssl libc6-compat

# Copy lockfile and package.json to install from root
COPY package.json package-lock.json turbo.json ./
COPY apps ./apps
COPY packages ./packages

# Install all monorepo deps including tsx, turbo, typescript
RUN npm install --legacy-peer-deps

# Generate Prisma client

RUN npx prisma generate --schema=packages/db/prisma/schema.prisma
# RUN npx prisma migrate dev --schema=packages/db/prisma/schema.prismacd 

# --------------------
# Stage 2: Dev Runtime for apps/http
# --------------------
FROM node:20-alpine AS dev

WORKDIR /app

RUN corepack enable npm
RUN apk add --no-cache openssl libc6-compat

ENV LD_PRELOAD=/lib/libc.so.6

# Copy everything from installer
COPY --from=installer /app /app

WORKDIR /app/apps/http

EXPOSE 3000

# Run dev using turbo (recommended), or fallback to workspace script
CMD ["npm", "run", "dev"]
