services:
  http:
    container_name: http
    build:
      context: ../../
      dockerfile: apps/http/Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      # Mount only the necessary app code and db package
      - ../../apps/http:/app
      - ../../packages/db:/packages/db
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    environment:
      # Make sure this matches your Prisma client and DB config
      DATABASE_URL: "postgresql://neondb_owner:npg_Dkx3RVOs6ZTz@ep-soft-pine-a80oge99-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metaverse
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
