services: 
  db:
    image: postgres:15-alpine
    container_name: dev-db
    ports:
      - "5332:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnet

  livekit:
    image: livekit/livekit-server:latest
    container_name: dev-livekit
    ports:
      - "7880:7880"   # HTTP API
      - "7881:7881"   # WebRTC over TCP
      - "7882:7882/udp"  # WebRTC over UDP
    environment:
      LIVEKIT_KEYS: "devkey: devsecret"
    command: --dev --bind 0.0.0.0
    networks:
      - devnet

  ws:
    build:
      context: .
      dockerfile: apps/ws/Dockerfile.dev
    container_name: dev-ws
    ports:
      - "3001:3001"
    environment:
       DATABASE_URL: "postgresql://neondb_owner:npg_Dkx3RVOs6ZTz@ep-soft-pine-a80oge99-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - livekit
    networks:
      - devnet

  http:
    build:
      context: .
      dockerfile: apps/http/Dockerfile.dev
      args:
        DATABASE_URL: "postgresql://neondb_owner:npg_Dkx3RVOs6ZTz@ep-soft-pine-a80oge99-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    container_name: dev-http
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_Dkx3RVOs6ZTz@ep-soft-pine-a80oge99-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
      LIVEKIT_API_KEY: "devkey"
      LIVEKIT_API_SECRET: "devsecret"
      LIVEKIT_URL: "ws://livekit:7880"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - livekit
    networks:
      - devnet

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    container_name: dev-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_LIVEKIT_URL: "ws://localhost:7880"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - http
      - ws
      - livekit
    networks:
      - devnet

volumes:
  postgres-data:

networks:
  devnet:
