services:
  ws:
    container_name: ws
    build:
      context: ../../
      dockerfile: apps/ws/Dockerfile.dev
      target: dev  # 👈 important: use the second stage of the Dockerfile
    ports:
      - "3001:3001"  # container port is 3000 as exposed in Dockerfile
    volumes:
      - ../../:/app:cached
      - /app/node_modules  # prevent host overrides
    working_dir: /app/apps/ws
    command: ["npm", "run", "dev"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - http

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metaverse
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: